{"uuid": "e11bbd2b-8a87-4567-bc5f-17a7198aef9f", "children": ["6dcba0da-6d93-4075-b5b4-ee11b196e98d"], "befores": [{"name": "selenium", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n\tGetHandleVerifier [0x00007FF622A6EEA2+31554]\n\t(No symbol) [0x00007FF6229E7ED9]\n\t(No symbol) [0x00007FF6228A872A]\n\t(No symbol) [0x00007FF6228E0D2E]\n\t(No symbol) [0x00007FF6228DBB3B]\n\t(No symbol) [0x00007FF622928794]\n\t(No symbol) [0x00007FF622927DF0]\n\t(No symbol) [0x00007FF62291CDD3]\n\t(No symbol) [0x00007FF6228EA33B]\n\t(No symbol) [0x00007FF6228EAED1]\n\tGetHandleVerifier [0x00007FF622D78B1D+3217341]\n\tGetHandleVerifier [0x00007FF622DC5AE3+3532675]\n\tGetHandleVerifier [0x00007FF622DBB0E0+3489152]\n\tGetHandleVerifier [0x00007FF622B1E776+750614]\n\t(No symbol) [0x00007FF6229F375F]\n\t(No symbol) [0x00007FF6229EEB14]\n\t(No symbol) [0x00007FF6229EECA2]\n\t(No symbol) [0x00007FF6229DE16F]\n\tBaseThreadInitThunk [0x00007FFFB9B67374+20]\n\tRtlUserThreadStart [0x00007FFFBB29CC91+33]\n\n", "trace": "  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\_pytest\\fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Dell\\PycharmProjects\\Autotest_final\\src\\fixtures\\system\\browser.py\", line 20, in selenium\n    driver = Chrome(service=service, options=options)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Dell\\miniconda3\\envs\\Final_AT\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721369261165, "stop": 1721369264870}], "start": 1721369261165, "stop": 1721369265039}